#!/bin/bash
set -e

active=$1
if [ "$active" = "blue" ]; then
    passive=green
elif [ "$active" = "green" ]; then
    passive=blue
else
    echo "Unknown node $active"
    exit 1
fi

sed "s/proxy_pass http:\\/\\/node-[a-z]\+; \+# active/proxy_pass http:\/\/node-$active; # active/;
    s/proxy_pass http:\\/\\/node-[a-z]\+; \+# passive/proxy_pass http:\/\/node-$passive; # passive/" /etc/nginx/nginx.conf > /tmp/nginx.conf && cat /tmp/nginx.conf >/etc/nginx/nginx.conf

sudo systemctl reload nginx
